#!/bin/bash
set -eEuo pipefail

# =========================================================
# Archium Installer - Install Phase
# =========================================================

# ---------------------------
# Theming / UI options
# ---------------------------
export DIALOGRC="${DIALOGRC:-/etc/archium-dialogrc}"

TITLE="Archium Linux Installer"
ERROR_TITLE=" Error "
INSTALL_TITLE=" Installing Archium "
SUCCESS_TITLE=" Success "

# ---------------------------
# Dialog sizing
# ---------------------------
DIALOG_H=12
DIALOG_W=68

# ---------------------------
# Script self-location
# ---------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SETUP_SCRIPT="$SCRIPT_DIR/archium-setup.sh"

# ---------------------------
# Load config generated by setup
# ---------------------------
load_installer_config() {
    if [[ -f /tmp/archium.conf ]]; then
        # shellcheck disable=SC1091
        source /tmp/archium.conf
    else
        dialog --clear --backtitle "$TITLE" --title "$ERROR_TITLE" \
            --msgbox "No configuration found. Returning to setup." 8 50
        exec "$SETUP_SCRIPT"
    fi

    : "${FS_TYPE:=ext4}"
    : "${GPU_STACK:=generic}"
}
trap 'echo "Installer crashed near line $LINENO" >/tmp/archium-install-error.log' ERR

# ---------------------------
# Boot mode detection
# ---------------------------
detect_boot_mode() {
    BOOT_MODE="bios"
    if [[ -d /sys/firmware/efi ]]; then
        BOOT_MODE="uefi"
    fi
}

# ---------------------------
# CPU / kernel target detection
# ---------------------------
detect_kernel_target() {
    KERNEL="x86-64"

    local cpu_vendor cpu_family cpu_model base_level
    cpu_vendor="$(grep -m1 "vendor_id" /proc/cpuinfo | awk '{print $3}')"
    cpu_family="$(LANG=C lscpu | awk -F: '/CPU family/ {gsub(/ /,""); print $2}')"
    cpu_model="$(LANG=C lscpu | awk -F: '/Model:/ {gsub(/ /,""); print $2}')"

    if grep -qw avx512 /proc/cpuinfo; then
        base_level="x86-64-v4"
    elif grep -qw avx2 /proc/cpuinfo; then
        base_level="x86-64-v3"
    elif grep -qw sse4_2 /proc/cpuinfo; then
        base_level="x86-64-v2"
    else
        base_level="x86-64"
    fi

    KERNEL="$base_level"

    if [[ "$cpu_vendor" == "GenuineIntel" ]]; then
        case "$cpu_model" in
            78|94|142|158) KERNEL="skylake" ;;
            151|154) KERNEL="alderlake" ;;
        esac
    elif [[ "$cpu_vendor" == "AuthenticAMD" ]]; then
        case "$cpu_family" in
            23) KERNEL="znver2" ;;
            25) KERNEL="znver3" ;;
            26) KERNEL="znver4" ;;
            27) KERNEL="znver5" ;;
        esac
    fi

    case "$base_level" in
        x86-64-v4)
            if [[ "$KERNEL" == x86-64* ]]; then
                KERNEL="x86-64-v4"
            fi
            ;;
        x86-64-v3)
            if [[ "$KERNEL" == "x86-64" || "$KERNEL" == "x86-64-v2" ]]; then
                KERNEL="x86-64-v3"
            fi
            ;;
        x86-64-v2)
            if [[ "$KERNEL" == "x86-64" ]]; then
                KERNEL="x86-64-v2"
            fi
            ;;
    esac
}

# ---------------------------
# Partition suffix helper
# nvme/mmc devices need p1/p2
# ---------------------------
get_part_suffix() {
    local dev="$1"
    if [[ "$dev" == *"nvme"* || "$dev" == *"mmcblk"* ]]; then
        printf "p"
    else
        printf ""
    fi
}

# ---------------------------
# Generic partition path helper
# ---------------------------
get_partition_path() {
    local dev="$1"
    local number="$2"
    local suffix
    suffix="$(get_part_suffix "$dev")"
    printf "%s%s%s" "$dev" "$suffix" "$number"
}

# ---------------------------
# Filesystem helpers
# ---------------------------
format_linux_partition() {
    local part="$1"

    case "$FS_TYPE" in
        ext4)
            mkfs.ext4 -F "$part"
            ;;
        btrfs)
            mkfs.btrfs -f "$part"
            ;;
        *)
            echo "Unsupported filesystem: $FS_TYPE"
            exit 1
            ;;
    esac
}

mount_root_filesystem() {
    local root_part="$1"

    case "$FS_TYPE" in
        ext4)
            mount "$root_part" /mnt
            ;;
        btrfs)
            mount "$root_part" /mnt
            btrfs subvolume create /mnt/@
            btrfs subvolume create /mnt/@home
            umount /mnt

            mount -o subvol=@ "$root_part" /mnt
            mkdir -p /mnt/home
            mount -o subvol=@home "$root_part" /mnt/home
            ;;
        *)
            echo "Unsupported filesystem: $FS_TYPE"
            exit 1
            ;;
    esac
}

mount_extra_filesystem() {
    local part="$1"
    local target="$2"

    mkdir -p "/mnt${target}"

    case "$FS_TYPE" in
        ext4)
            mount "$part" "/mnt${target}"
            ;;
        btrfs)
            mount "$part" "/mnt${target}"
            ;;
        *)
            echo "Unsupported filesystem: $FS_TYPE"
            exit 1
            ;;
    esac
}

sanitize_fstab_for_btrfs() {
    [[ "$FS_TYPE" == "btrfs" ]] || return 0
    [[ -f /mnt/etc/fstab ]] || return 0

    # Remove subvolid=... from btrfs entries; keep subvol=...
    sed -Ei '/[[:space:]]btrfs[[:space:]]/ s/(,)?subvolid=[0-9]+//g' /mnt/etc/fstab
    sed -Ei '/[[:space:]]btrfs[[:space:]]/ s/,,+/,/g; /[[:space:]]btrfs[[:space:]]/ s/,([[:space:]])/\1/g; /[[:space:]]btrfs[[:space:]]/ s/defaults,/defaults,/g' /mnt/etc/fstab
}

# ---------------------------
# Main drive partitioning
# UEFI: p1 EFI, p2 root
# BIOS: p1 BIOS boot, p2 root
# ---------------------------
partition_main_drive_uefi() {
    local dev="$1"

    sed -e 's/\s*#.*//' <<EOF | fdisk "$dev"
g
n
1

+512M
t
1
n
2


w
EOF
}

partition_main_drive_bios() {
    local dev="$1"

    sed -e 's/\s*#.*//' <<EOF | fdisk "$dev"
g
n
1

+2M
t
4
n
2


w
EOF
}

# ---------------------------
# Extra drives
# EXTRA_MOUNTS format: DEVICE:TARGET
# Example:
# /dev/sdb:/home
# /dev/sdc:/HDD_2T
# ---------------------------

prepare_main_drive() {
    local dev="$1"
    local root_part efi_part

    echo "STEP 1: Partitioning main drive..."
    wipefs -af "$dev"
    sgdisk --zap-all "$dev" >/dev/null 2>&1 || true
    partprobe "$dev" >/dev/null 2>&1 || true
    udevadm settle
    sleep 1

    if [[ "$BOOT_MODE" == "uefi" ]]; then
        partition_main_drive_uefi "$dev"
    else
        partition_main_drive_bios "$dev"
    fi
    partprobe "$dev" >/dev/null 2>&1 || true
    udevadm settle
    sleep 1

    root_part="$(get_partition_path "$dev" 2)"

    echo "STEP 2: Formatting main drive..."
    format_linux_partition "$root_part"

    if [[ "$BOOT_MODE" == "uefi" ]]; then
        efi_part="$(get_partition_path "$dev" 1)"
        mkfs.fat -F 32 "$efi_part"
    fi

    echo "STEP 3: Mounting main drive..."
    mount_root_filesystem "$root_part"

    if [[ "$BOOT_MODE" == "uefi" ]]; then
        mkdir -p /mnt/boot
        mount "$efi_part" /mnt/boot
    fi
}
prepare_extra_drives() {
    if [[ -z "${EXTRA_MOUNTS:-}" || -z "${EXTRA_MOUNTS// }" ]]; then
        return 0
    fi

    echo "STEP 3b: Preparing extra drives..."

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -z "$line" ]] && continue

        local dev target extra_part
        dev="$(printf '%s' "$line" | cut -d: -f1)"
        target="$(printf '%s' "$line" | cut -d: -f2-)"

        [[ -z "$dev" || -z "$target" ]] && continue

        wipefs -af "$dev"
        sgdisk --zap-all "$dev" >/dev/null 2>&1 || true
        partprobe "$dev" >/dev/null 2>&1 || true
        udevadm settle

        sed -e 's/\s*#.*//' <<EOF | fdisk "$dev"
g
n
1


w
EOF

        partprobe "$dev" >/dev/null 2>&1 || true
        udevadm settle
        sleep 1

        extra_part="$(get_partition_path "$dev" 1)"

        format_linux_partition "$extra_part"
        mount_extra_filesystem "$extra_part" "$target"
    done <<< "$(printf '%b' "$EXTRA_MOUNTS")"
}

# ---------------------------
# Install base system
# ---------------------------
install_base_system() {
    echo "STEP 4: Installing packages (this takes time)..."

    pacstrap -K /mnt \
        --noconfirm \
        --needed \
        $ARCH_PACKAGE_LIST \
        "linux-archium-tkg-$KERNEL" \
        "linux-archium-tkg-$KERNEL-headers" \
        linux-archium-tkg-x86-64 \
        linux-archium-tkg-x86-64-headers \
        mkinitcpio \
        qt6-multimedia-ffmpeg
}

# ---------------------------
# Generate fstab
# ---------------------------
generate_fstab() {
    echo "STEP 5: Generating fstab..."
    genfstab -U /mnt > /mnt/etc/fstab
    sanitize_fstab_for_btrfs
}


get_root_partition_uuid() {
    local root_part
    root_part="$(findmnt -nro SOURCE /mnt)"
    blkid -s UUID -o value "$root_part"
}

# ---------------------------
# Verify Grub
# ---------------------------
verify_grub_config() {
    local expected_uuid grub_cfg linux_line actual_uuid

    grub_cfg="/mnt/boot/grub/grub.cfg"
    expected_uuid="$(blkid -s UUID -o value "$(findmnt -nro SOURCE /mnt)")"

    [[ -n "$expected_uuid" ]] || {
        echo "Could not determine installed root UUID."
        return 1
    }

    [[ -f "$grub_cfg" ]] || {
        echo "Missing $grub_cfg"
        return 1
    }

    linux_line="$(grep -m1 -E '^[[:space:]]*linux[[:space:]]+/boot/' "$grub_cfg" || true)"
    actual_uuid="$(printf '%s\n' "$linux_line" | grep -o 'root=UUID=[^[:space:]]*' | cut -d= -f3 || true)"

    if [[ -z "$actual_uuid" ]]; then
        echo "GRUB config does not contain root=UUID=..."
        return 1
    fi

    if [[ "$actual_uuid" != "$expected_uuid" ]]; then
        echo "GRUB root UUID mismatch."
        echo "Expected: $expected_uuid"
        echo "Found:    $actual_uuid"
        return 1
    fi

    echo "GRUB root UUID verified: $actual_uuid"
    return 0
}

# ---------------------------
# Post-install config handoff
# ---------------------------
write_postinstall_config() {
    echo "STEP 6: Writing post-install config..."

    {
        printf "SYSTEM_HOSTNAME=%q\n" "$SYSTEM_HOSTNAME"
        printf "USERNAME=%q\n" "$USERNAME"
        printf "ROOT_PASS=%q\n" "$ROOT_PASS"
        printf "USER_PASS=%q\n" "$USER_PASS"
        printf "REAL_PATH=%q\n" "$REAL_PATH"
        printf "SELECTED_KBL=%q\n" "$SELECTED_KBL"
        printf "SELECTED_LOCALE=%q\n" "$SELECTED_LOCALE"
        printf "REGION=%q\n" "$REGION"
        printf "CITY=%q\n" "$CITY"
        printf "AUR_PACKAGE_LIST=%q\n" "$AUR_PACKAGE_LIST"
        printf "NVIDIA_AUR_DRIVER=%q\n" "$NVIDIA_AUR_DRIVER"
        printf "KERNEL=%q\n" "$KERNEL"
        printf "FS_TYPE=%q\n" "$FS_TYPE"
        printf "GPU_VENDOR=%q\n" "$GPU_VENDOR"
        printf "GPU_STACK=%q\n" "$GPU_STACK"
    } > /mnt/root/archium-post.conf
}

# ---------------------------
# Configure installed system
# ---------------------------
configure_installed_system() {
    echo "STEP 7: Configuring system inside chroot..."

   arch-chroot /mnt /bin/bash <<'EOF'
set -eEuo pipefail
source /root/archium-post.conf

enable_multilib_and_pacman_tweaks() {
    sed -i 's/^#Color/Color/' /etc/pacman.conf
    sed -i 's/^#ParallelDownloads.*/ParallelDownloads = 8/' /etc/pacman.conf
    sed -i '/\[multilib\]/,/Include/s/^#//' /etc/pacman.conf
}

configure_nvidia_graphics() {
    echo "Applying NVIDIA graphics configuration..."

    mkdir -p /etc/modprobe.d
    mkdir -p /etc/environment.d

    cat > /etc/modprobe.d/nvidia.conf <<'EOF_NVIDIA'
options nvidia_drm modeset=1
EOF_NVIDIA

    cat > /etc/modprobe.d/blacklist-nouveau.conf <<'EOF_NOUVEAU'
blacklist nouveau
options nouveau modeset=0
EOF_NOUVEAU

    cat > /etc/environment.d/90-archium-nvidia.conf <<'EOF_ENV'
GBM_BACKEND=nvidia-drm
__GLX_VENDOR_LIBRARY_NAME=nvidia
LIBVA_DRIVER_NAME=nvidia
EOF_ENV

    if grep -q '^MODULES=' /etc/mkinitcpio.conf; then
        sed -i 's/^MODULES=.*/MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)/' /etc/mkinitcpio.conf
    else
        echo 'MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)' >> /etc/mkinitcpio.conf
    fi
}

configure_amd_graphics() {
    echo "Applying AMDGPU configuration..."

    mkdir -p /etc/environment.d
    cat > /etc/environment.d/90-archium-amd.conf <<'EOF_AMD'
AMD_VULKAN_ICD=RADV
EOF_AMD
}

configure_intel_graphics() {
    echo "Applying Intel graphics configuration..."

    mkdir -p /etc/environment.d
    cat > /etc/environment.d/90-archium-intel.conf <<'EOF_INTEL'
# Intel graphics uses Mesa defaults on Archium.
EOF_INTEL
}

configure_generic_graphics() {
    echo "Applying generic graphics configuration..."
    true
}

configure_gpu_stack() {
    case "${GPU_STACK:-generic}" in
        nvidia)
            configure_nvidia_graphics
            ;;
        amd)
            configure_amd_graphics
            ;;
        intel)
            configure_intel_graphics
            ;;
        nouveau|generic|*)
            configure_generic_graphics
            ;;
    esac
}

echo "$SYSTEM_HOSTNAME" > /etc/hostname
SELECTED_LOCALE="$(echo "$SELECTED_LOCALE" | awk '{print $1}')"

ln -sf "/usr/share/zoneinfo/$REGION/$CITY" /etc/localtime
hwclock --systohc

sed -i "s/^#$SELECTED_LOCALE/$SELECTED_LOCALE/" /etc/locale.gen
locale-gen
echo "LANG=$SELECTED_LOCALE" > /etc/locale.conf

echo "root:$ROOT_PASS" | chpasswd
useradd -m -G wheel "$USERNAME"
echo "$USERNAME:$USER_PASS" | chpasswd

KBL_RAW="$(printf '%s' "$SELECTED_KBL" | tr -d '"')"
PRIMARY_KBL="$(printf '%s' "$KBL_RAW" | awk '{print $1}')"

if [[ -z "$PRIMARY_KBL" ]]; then
    PRIMARY_KBL="us"
fi

if localectl list-keymaps | grep -Fxq "$PRIMARY_KBL"; then
    localectl --no-convert set-keymap "$PRIMARY_KBL" || true
    echo "KEYMAP=$PRIMARY_KBL" > /etc/vconsole.conf
else
    PRIMARY_KBL="us"
    echo "KEYMAP=us" > /etc/vconsole.conf
fi
localectl --no-convert set-x11-keymap "$PRIMARY_KBL" || true

echo "vm.swappiness = 10" > /etc/sysctl.d/99-swappiness.conf
sed -i "s/^#MAKEFLAGS.*/MAKEFLAGS=\"-j\$(nproc)\"/" /etc/makepkg.conf

mkdir -p "/home/$USERNAME/.steam/steam"
echo "unShaderBackgroundProcessingThreads $(nproc)" > "/home/$USERNAME/.steam/steam/steam_dev.cfg"
chown -R "$USERNAME:$USERNAME" "/home/$USERNAME/.steam"

enable_multilib_and_pacman_tweaks
configure_gpu_stack
mkinitcpio -P

if grep -q '^GRUB_DISTRIBUTOR=' /etc/default/grub; then
    sed -i 's/^GRUB_DISTRIBUTOR=.*/GRUB_DISTRIBUTOR="Archium"/' /etc/default/grub
else
    echo 'GRUB_DISTRIBUTOR="Archium"' >> /etc/default/grub
fi

echo "Waiting for disks to settle..."
sync
partprobe || true
udevadm settle
sleep 2

if [[ -d /sys/firmware/efi ]]; then
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=Archium
else
    grub-install --target=i386-pc "$REAL_PATH"
fi

grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable sddm
systemctl enable NetworkManager
systemctl enable ufw

echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/10-installer

pacman -S --noconfirm --needed rust

sudo -u "$USERNAME" bash <<'EOF_PARU'
set -eEuo pipefail
workdir="$(mktemp -d /tmp/paru-build.XXXXXX)"
trap 'rm -rf "$workdir"' EXIT
cd "$workdir"
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si --noconfirm
EOF_PARU

AUR_PACKAGE_LIST="$(echo "$AUR_PACKAGE_LIST" | tr -d '"')"

if [[ -n "$NVIDIA_AUR_DRIVER" ]]; then
    AUR_PACKAGE_LIST="$NVIDIA_AUR_DRIVER $AUR_PACKAGE_LIST"
fi

if [[ -n "$AUR_PACKAGE_LIST" ]]; then
    sudo -u "$USERNAME" paru -S --noconfirm --needed $AUR_PACKAGE_LIST
    mkinitcpio -P
fi

if echo "$AUR_PACKAGE_LIST" | grep -qw "winboat-bin"; then
    systemctl enable docker.service
    usermod -aG docker "$USERNAME"
fi

if echo "$AUR_PACKAGE_LIST" | grep -qw "bluez"; then
    systemctl enable bluetooth.service
fi

if echo "$AUR_PACKAGE_LIST" | grep -qw "cups"; then
    systemctl enable cups.service
fi

if echo "$AUR_PACKAGE_LIST" | grep -qw "reflector"; then
    reflector --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist
    printf '%s\n' \
        '--save /etc/pacman.d/mirrorlist' \
        '--protocol https' \
        '--latest 10' \
        '--sort rate' > /etc/xdg/reflector/reflector.conf
    systemctl enable reflector.timer
fi

if echo "$AUR_PACKAGE_LIST" | grep -qw "piper"; then
    pacman -S --noconfirm libratbag
    systemctl enable libratbag.service
fi

if echo "$AUR_PACKAGE_LIST" | grep -qw "lact"; then
    systemctl enable lactd.service

    if [[ -f /etc/default/grub ]] && ! grep -q "amdgpu.ppfeaturemask" /etc/default/grub; then
        sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT="/GRUB_CMDLINE_LINUX_DEFAULT="amdgpu.ppfeaturemask=0xffffffff /' /etc/default/grub
        grub-mkconfig -o /boot/grub/grub.cfg
    fi
fi

if [[ "${GPU_STACK:-generic}" == "nvidia" ]] && echo "$AUR_PACKAGE_LIST" | grep -qE '(^|[[:space:]])(nvidia-oc|gwe)($|[[:space:]])'; then
    command -v nvidia-xconfig >/dev/null 2>&1 && \
        nvidia-xconfig --cool-bits=28 --allow-empty-initial-configuration || true

    if echo "$AUR_PACKAGE_LIST" | grep -qw "nvidia-oc"; then
        systemctl enable nvidia_oc.service 2>/dev/null || true
    fi
fi

if echo "$AUR_PACKAGE_LIST" | grep -qw "amdgpu-fan"; then
    systemctl enable amdgpu-fan.service
fi

rm -f /etc/sudoers.d/10-installer
echo "%wheel ALL=(ALL) ALL" > /etc/sudoers.d/10-installer
rm -f /root/archium-post.conf

printf 'NAME="Archium Linux"\nPRETTY_NAME="Archium Linux"\nID=archium\nBUILD_ID=rolling\nANSI_COLOR="38;2;23;147;209"\nHOME_URL="https://github.com/N3kowarrior/archium-linux"\nDOCUMENTATION_URL="https://github.com/N3kowarrior/archium-linux"\nSUPPORT_URL="https://github.com/N3kowarrior/archium-linux/issues"\nBUG_REPORT_URL="https://github.com/N3kowarrior/archium-linux/issues"\nLOGO=archium\n' > /etc/os-release
printf 'DISTRIB_ID=Archium\nDISTRIB_RELEASE=rolling\nDISTRIB_DESCRIPTION="Archium Linux"\n' > /etc/lsb-release
echo "Archium Linux \\r (\\l)" > /etc/issue
EOF
}

# ---------------------------
# Copy bundled wallpapers
# ---------------------------
install_archium_wallpapers() {
    echo "STEP 8: Installing Archium wallpapers..."
    mkdir -p /mnt/usr/share/wallpapers/Archium
        if [[ -d /usr/share/wallpapers/Archium ]] && find /usr/share/wallpapers/Archium -mindepth 1 -print -quit | grep -q .; then
        cp -a /usr/share/wallpapers/Archium/. /mnt/usr/share/wallpapers/Archium/
        find /mnt/usr/share/wallpapers/Archium -type d -exec chmod 755 {} +
        find /mnt/usr/share/wallpapers/Archium -type f -exec chmod 644 {} +
    fi
}

# ---------------------------
# Main install flow
# ---------------------------
perform_install() {
    prepare_main_drive "$REAL_PATH"
    prepare_extra_drives
    install_base_system
    generate_fstab
    write_postinstall_config
    configure_installed_system
    verify_grub_config
    install_archium_wallpapers
}

# ---------------------------
# Run installer UI
# ---------------------------
main() {
    load_installer_config
    detect_boot_mode
    detect_kernel_target

    perform_install 2>&1 | dialog --clear --backtitle "$TITLE" --title "$INSTALL_TITLE" --programbox 22 80

    dialog --clear --backtitle "$TITLE" --title "$SUCCESS_TITLE" --msgbox "Archium is installed!" 8 50
    clear
}

main
